package com.example.demo.dao;

import com.example.demo.domain.TAddress;

import java.util.List;

public interface TAddressDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_address
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_address
     *
     * @mbg.generated
     */
    int insert(TAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_address
     *
     * @mbg.generated
     */
    int insertSelective(TAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_address
     *
     * @mbg.generated
     */
    TAddress selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_address
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_address
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TAddress record);
    TAddress selectSelectivekey(TAddress tAddress);
    List<TAddress> selectAll();
}