package com.example.demo.dao;

import com.example.demo.domain.TDictAreas;

import java.util.List;

public interface TDictAreasDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dict_areas
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dict_areas
     *
     * @mbg.generated
     */
    int insert(TDictAreas record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dict_areas
     *
     * @mbg.generated
     */
    int insertSelective(TDictAreas record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dict_areas
     *
     * @mbg.generated
     */
    TDictAreas selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dict_areas
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TDictAreas record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dict_areas
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TDictAreas record);
    List<TDictAreas> selectAll();
}