package com.example.demo.dao;

import com.example.demo.domain.TDictProvinces;

import java.util.List;

public interface TDictProvincesDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dict_provinces
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dict_provinces
     *
     * @mbg.generated
     */
    int insert(TDictProvinces record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dict_provinces
     *
     * @mbg.generated
     */
    int insertSelective(TDictProvinces record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dict_provinces
     *
     * @mbg.generated
     */
    TDictProvinces selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dict_provinces
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TDictProvinces record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dict_provinces
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TDictProvinces record);
    List<TDictProvinces> selectAll();
}